version: "3"
services:
  mongodb:
    image: mongo
    restart: unless-stopped
    ports:
      - ${DB_PORT}:27017
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: .
    restart: unless-stopped
    ports:
      - ${RUNNING_PORT}:3000
    environment:
      - DB_HOST=mongodb
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
volumes:
  db: